db-uri = "postgresql://marcelmanduca@localhost:5432/michele_homolog"
db-schemas = "public"
db-anon-role = "anon"
server-port = 54320
server-host = "127.0.0.1"
jwt-secret = "super-secret-jwt-token-with-at-least-32-characters-long"
jwt-secret-is-base64 = false
