/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnuncieRouteImport } from './routes/anuncie'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImovelCodeRouteImport } from './routes/imovel.$code'
import { Route as ApiPublicHooksSyncPropertiesRouteImport } from './routes/api/public/hooks/sync-properties'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnuncieRoute = AnuncieRouteImport.update({
  id: '/anuncie',
  path: '/anuncie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImovelCodeRoute = ImovelCodeRouteImport.update({
  id: '/imovel/$code',
  path: '/imovel/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncPropertiesRoute =
  ApiPublicHooksSyncPropertiesRouteImport.update({
    id: '/api/public/hooks/sync-properties',
    path: '/api/public/hooks/sync-properties',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/imovel/$code': typeof ImovelCodeRoute
  '/api/public/hooks/sync-properties': typeof ApiPublicHooksSyncPropertiesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/imovel/$code': typeof ImovelCodeRoute
  '/api/public/hooks/sync-properties': typeof ApiPublicHooksSyncPropertiesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anuncie': typeof AnuncieRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/imovel/$code': typeof ImovelCodeRoute
  '/api/public/hooks/sync-properties': typeof ApiPublicHooksSyncPropertiesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/auth'
    | '/buscar'
    | '/sitemap.xml'
    | '/imovel/$code'
    | '/api/public/hooks/sync-properties'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anuncie'
    | '/auth'
    | '/buscar'
    | '/sitemap.xml'
    | '/imovel/$code'
    | '/api/public/hooks/sync-properties'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anuncie'
    | '/auth'
    | '/buscar'
    | '/sitemap.xml'
    | '/imovel/$code'
    | '/api/public/hooks/sync-properties'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnuncieRoute: typeof AnuncieRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ImovelCodeRoute: typeof ImovelCodeRoute
  ApiPublicHooksSyncPropertiesRoute: typeof ApiPublicHooksSyncPropertiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anuncie': {
      id: '/anuncie'
      path: '/anuncie'
      fullPath: '/anuncie'
      preLoaderRoute: typeof AnuncieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imovel/$code': {
      id: '/imovel/$code'
      path: '/imovel/$code'
      fullPath: '/imovel/$code'
      preLoaderRoute: typeof ImovelCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-properties': {
      id: '/api/public/hooks/sync-properties'
      path: '/api/public/hooks/sync-properties'
      fullPath: '/api/public/hooks/sync-properties'
      preLoaderRoute: typeof ApiPublicHooksSyncPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnuncieRoute: AnuncieRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ImovelCodeRoute: ImovelCodeRoute,
  ApiPublicHooksSyncPropertiesRoute: ApiPublicHooksSyncPropertiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
